version: '3.8'

services:
  api:
    command:
      ['rails', 'server', '-b', '0.0.0.0', '-p', '80', '-e', 'development']
    environment:
      RAILS_ENV: development
    volumes:
      - ./api_server:/app
  web:
    command: ['yarn', 'run', 'dev', '-p', '80']
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
