version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${DB_ADMIN}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
  elasticsearch:
    image: elasticsearch:7.9.1
    environment:
      discovery.type: single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  api:
    build: api_server
    command:
      ['rails', 'server', '-b', '0.0.0.0', '-p', '80', '-e', 'development']
    volumes:
      - ./api_server:/app
    ports:
      - '3000:80'
    environment:
      DB_HOST: '${DB_HOST}'
      DB_ADMIN: '${DB_ADMIN}'
      DB_PASSWORD: '${DB_PASSWORD}'
      ELASTICSEARCH_URL: elasticsearch
    depends_on:
      - db
      - elasticsearch
volumes:
  db:
  elasticsearch:
